#!/bin/bash
brew install htop
brew install zsh
brew install git
brew install vim
brew install wget
brew install tree
brew install pstree
brew install automake
brew install rlwrap
brew install autojump
brew install tig
brew install the_silver_searcher
brew install go
brew install peco
brew install bvi
brew install tmux
brew install yajl
brew install reattach-to-user-namespace
brew install pinentry-mac
brew install google-cloud-sdk
brew install openjdk
brew install jq
